fixed the bug on task 0

diff --git a/0x0F-load_balancer/0-custom_http_response-header b/0x0F-load_balancer/0-custom_http_response-header
--- a/0x0F-load_balancer/0-custom_http_response-header
+++ b/0x0F-load_balancer/0-custom_http_response-header
@@ -1,49 +1,60 @@
 #!/usr/bin/env bash
-# Configure Nginx so that its HTTP response contains a custom header
-# HTTP response contains a custom header (on web-01 and web-02)
+# duplicate web-01 to web-02
+echo -e "Updating and doing some minor checks...\n"
+function install() {
+	command -v "$1" &> /dev/null
 
-# Update the package list
-sudo apt update
-
-# Install Nginx
-sudo apt install -y nginx
-
-# Define the custom header value
-custom_header_value="$(hostname)"
-
-# Update the default Nginx configuration file
-sudo tee /etc/nginx/sites-available/default <<EOF
-server {
-    listen 80;
-    listen [::]:80;
-
-    server_name _;
-
-    error_page 404 /404.html;
-    add_header X-Served-By $custom_header_value;
-
-    location / {
-        root /var/www/html;
-        index index.html;
-    }
-
-    location /redirect_me {
-        return 301 https://github.com/robberbadeia;
-    }
-
-    location /404 {
-        root /var/www/html;
-        internal;
-    }
-    # Remove the duplicate location block
-    location /custom_404.html {
-        internal;
-    }
+	#shellcheck disable=SC2181
+	if [ $? -ne 0 ]; then
+		echo -e "	Installing: $1$\n"
+		sudo apt-get update -y -qq && \
+			sudo apt-get install -y "$1" -qq
+		echo -e "\n"
+	else
+		echo -e "	${1} is already installed.\n"
+	fi
 }
-EOF
-
-# Test the Nginx configuration for syntax errors
-sudo nginx -t
-
-# Restart Nginx to apply the changes
-sudo systemctl restart nginx
+install nginx
+echo -e "\nSetting up some minor stuff.\n"
+sudo ufw allow 'Nginx HTTP'
+if [ -d "/var/www" ]; then
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+else
+	sudo mkdir -p /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+fi
+for dir in /var/www/{html,error}; do
+	if ! [ -d "$dir" ]; then
+		mkdir -p "$dir"
+	fi
+done
+echo "Hello World!" > /var/www/html/index.html
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
+server_config=\
+"server {
+		listen 80 default_server;
+		listen [::]:80 default_server;
+		root /var/www/html;
+		index index.html index.htm index.nginx-debian.html
+		server_name_;
+		add_header X-Served-By \$hostname;
+		location / {
+			try_files \$uri \$uri/ =404;
+		}
+		if (\$request_filename ~ redirect_me){
+			rewrite ^ https://th3-gr00t.tk/ permanent;
+		}
+		error_page 404 /error_404.html;
+		location = /error_404.html {
+			internal;
+		}
+}"
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+	sudo service nginx start
+else
+	sudo service nginx restart
+fi
